name: PR Builds x64

on:
  push:
    branches:
        - Dev
    paths-ignore:
        - "**.md"
        - "**.ini"
  pull_request:
    branches: [ Dev ]
    paths-ignore:
      - "**.md"
      - "**.ini"

jobs:
  windows64-netplay:
    env:
      DXSDK_DIR: "C:\\Program Files (x86)\\Microsoft DirectX SDK (June 2010)\\"
    name: "Windows Netplay"
    runs-on: windows-2019
    steps:
      - name: "Remove Redistributable"
        shell: cmd
        run: |
          MsiExec.exe /passive /X{F0C3E5D1-1ADE-321E-8167-68EF0DE699A5}
          MsiExec.exe /passive /X{1D8E6291-B0D5-35EC-8441-6616F567A0F7}
      - name: "Install DirectX SDK"
        shell: powershell
        run: |
          choco install directx-sdk
      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1   
      - name: "Checkout"
        uses: actions/checkout@v2.3.1
      - name: 'Fetch Git Tags'
        if: success()
        shell: bash
        run: |
          git fetch --prune --unshallow
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: "Build Netplay Dolphin"
        shell: cmd
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 ${{ github.workspace }}\Source\Dolphin.sln
      - name: "Package Netplay"
        working-directory: ${{ github.workspace }}
        run: |
          $env:FILE_DATE=(Get-Date -UFormat "%F")
          $env:FILE_NAME="${env:FILE_DATE}-${{ env.GIT_HASH }}-${{ env.GIT_TAG }}-win64-netplay.zip"
          mkdir artifact
          Xcopy /Y /E /I .\Data\Sys .\Binary\x64\Sys
          cd .\Binary\x64\
          fsutil file createnew portable.txt 0
          fsutil file createnew FIX-VCRUNTIME140-ERROR.txt 0
          echo "Download and install this: https://aka.ms/vs/16/release/vc_redist.x64.exe" > .\FIX-VCRUNTIME140-ERROR.txt
          7z a ${env:FILE_NAME} .\*
          move ${env:FILE_NAME} ..\..\artifact\
      - name: "Publish"
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: "windows64-netplay"
          path: "./artifact/"
  ubuntu64-netplay:
      name: "Ubuntu Netplay"
      runs-on: ubuntu-18.04
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: 'Fetch Git Tags'
          if: success()
          run: |
            git fetch --prune --unshallow
            echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
            echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
            echo "CURR_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        - name: "Install prerequisites"
          if: success()
          shell: bash
          run: |
            sudo dpkg --add-architecture amd64
            sudo apt update
            sudo apt install \
            cmake \
			make \
			ca-certificates \
			gcc \
			g++ \
            pkg-config \
            git \
			libavcodec-dev \
			libavformat-dev \
			libavutil-dev \
			libswscale-dev \
			libxi-dev \
			libxrandr-dev \
			libudev-dev \
			libevdev-dev \
			libsfml-dev \
			libminiupnpc-dev \
			libmbedtls-dev \
			libcurl4-openssl-dev \
			libhidapi-dev \
			libsystemd-dev \
			libbluetooth-dev \
			libasound2-dev \
			libpulse-dev \
			libpugixml-dev \
			libbz2-dev \
			libzstd-dev \
			liblzo2-dev \
			libpng-dev \
			libusb-1.0-0-dev gettext \
			libxxf86vm-dev \
			libxmu-dev
        - name: "Build Netplay Dolphin"
          if: success()
          working-directory: ${{ github.workspace }}
          run: |
            ./build-linux.sh
        - name: "Build Netplay AppImage"
          if: success()
          working-directory: ${{ github.workspace }}
          run: |
            ./build-appimage.sh
        - name: "Package Netplay"
          if: success()
          working-directory: ${{ github.workspace }}
          run: |
            mkdir artifact
            FILE_NAME=${{ env.CURR_DATE }}-${{ env.GIT_HASH }}-${{ env.GIT_TAG }}-linux-appimage-netplay.zip
            zip -r "${FILE_NAME}" ./*.AppImage*
            mv "${FILE_NAME}" ./artifact/
        - name: "Publish"
          if: success()
          uses: actions/upload-artifact@v2-preview
          with:
            name: "linux-netplay"
            path: "./artifact/"
  macOS64-netplay:
    name: "macOS Netplay"
    runs-on: macos-10.15
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Fetch Git Tags'
        if: success()
        run: |
          git fetch --prune --unshallow
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "CURR_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: "Install 10.14 SDK"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.14.sdk.tar.xz
          tar -xf MacOSX10.14.sdk.tar.xz
          rm MacOSX10.14.sdk.tar.xz
          sudo mv MacOSX10.14.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
      - name: "Download and Install prerequisites"
        if: success()
        shell: bash
        run: |
          wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
          tar -xf wxWidgets-3.1.3.tar.bz2
          rm wxWidgets-3.1.3.tar.bz2
          brew update
          brew upgrade cmake
          brew install \
          ffmpeg \
          libpng \
          libav \
          pkgconfig \
          libao \
          sound-touch \
          hidapi \
          create-dmg
      - name: "Cache wxWidgets 3.1.3"
        uses: actions/cache@v1
        env:
          cache-name: "wxWidgets-3.1.3-macOS"
        with:
          path: ./wxWidgets-3.1.3/build
          key: "wxWidgets-3.1.3-macOS-Catalina"
      - name: "Install wxWidgets 3.1.3"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          cd wxWidgets-3.1.3
          cd build
          ../configure
          make -j7
          sudo make install
      - name: "Build Netplay (No Codesigning)"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          mkdir build
          cd build
          cmake ..
          make -j7
      - name: "Package Netplay"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          FILE_NAME=${{ env.CURR_DATE }}-${{ env.GIT_HASH }}-${{ env.GIT_TAG }}-macOS-netplay.dmg
          echo "FILE_NAME=$(FILE_NAME)" >> $GITHUB_ENV
          cp -Rf Data/Sys build/Binaries/FPM\ Dolphin.app/Contents/Resources/
          mkdir artifact
          create-dmg --no-internet-enable \
            --volname "FPM Dolphin Installer" \
            --text-size 14 \
            --window-pos 200 120 \
            --window-size 590 610 \
            --icon-size 100 \
            --app-drop-link 440 196 \
            --icon "FPM Dolphin.app" 140 196 \
            --hide-extension "FPM Dolphin.app" \
            "${FILE_NAME}" \
            "./build/Binaries/"
          mv "${FILE_NAME}" artifact/
      - name: "Publish"
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: "macOS-netplay"
          path: "./artifact/"