name: PR Builds x64

on:
  push:
    branches:
        - Dev
    paths-ignore:
        - "**.md"
        - "**.ini"
  pull_request:
    branches: [ Dev ]
    paths-ignore:
      - "**.md"
      - "**.ini"

jobs:
  macOS:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Netplay]
        include:
          - build_type: Netplay
            artifact_name: macOS-netplay
            build_config: netplay
    name: "macOS ${{ matrix.build_type }}"
    runs-on: macos-10.15
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Fetch Git Tags'
        if: success()
        run: |
          git fetch --prune --unshallow
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "CURR_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: "Install 10.14 SDK"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.14.sdk.tar.xz
          tar -xf MacOSX10.14.sdk.tar.xz
          rm MacOSX10.14.sdk.tar.xz
          sudo mv MacOSX10.14.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
      - name: "Download and Install prerequisites"
        if: success()
        shell: bash
        run: |
          rm '/usr/local/bin/2to3' || true
          echo "HOMEBREW_NO_AUTO_UPDATE=1" >> $GITHUB_ENV
          brew upgrade cmake
          brew install \
          ffmpeg \
          libpng \
          libav \
          pkgconfig \
          libao \
          sound-touch \
          hidapi
      - name: "Build ${{ matrix.build_type }} Dolphin"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          CERTIFICATE_MACOS_APPLICATION: ${{ secrets.CERTIFICATE_MACOS_APPLICATION }}
        run: |
          export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
          chmod +x ./build-mac.sh && ./build-mac.sh ${{ matrix.build_config }}
          mkdir artifact
          FILE_NAME=${{ env.CURR_DATE }}-${{ env.GIT_HASH }}-${{ env.GIT_TAG }}-${{ matrix.artifact_name }}
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
      - name: "Codesign ${{ matrix.build_type}} Dolphin"
        if: success() && env.CERTIFICATE_MACOS_APPLICATION != null
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          CERTIFICATE_MACOS_APPLICATION: ${{ secrets.CERTIFICATE_MACOS_APPLICATION }}
          CERTIFICATE_MACOS_PASSWORD: ${{ secrets.CERTIFICATE_MACOS_PASSWORD }}
        run: |
          chmod +x Tools/load-macos-certs-ci.sh && ./Tools/load-macos-certs-ci.sh
          mkdir -p ~/private_keys/
          echo '${{ secrets.APPLE_CONNECT_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
          
          /usr/bin/codesign -f -s "${{ secrets.APPLE_IDENTITY_HASH }}" --deep --options runtime --entitlements Source/Core/DolphinWX/Entitlements.plist ./build/Binaries/Ishiiruka\ Dolphin.app
      - name: "Package, Sign and Notarize Netplay Release DMG"
        if: success() && matrix.build_type == 'Netplay' && env.CERTIFICATE_MACOS_APPLICATION != null
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          CERTIFICATE_MACOS_APPLICATION: ${{ secrets.CERTIFICATE_MACOS_APPLICATION }}
        run: |
          chmod +x Tools/create-dmg/run.sh 
          ./Tools/create-dmg/run.sh --no-internet-enable \
            --volname "P+ Dolphin Installer" \
            --volicon "Data/ishiiruka.icns" \
            --background "Data/fpm_dmg_background.png" \
            --text-size 14 \
            --window-pos 200 120 \
            --window-size 590 610 \
            --icon-size 100 \
            --app-drop-link 440 196 \
            --icon "Dolphin.app" 140 196 \
            --hide-extension "Dolphin.app" \
            "${{ env.FILE_NAME }}.dmg" \
            "./build/Binaries/"
          mv "${{ env.FILE_NAME }}.dmg" artifact/
          /usr/bin/codesign -f -s "${{ secrets.APPLE_IDENTITY_HASH }}" --deep --options runtime ./artifact/${{ env.FILE_NAME }}.dmg
          chmod +x Tools/notarize_netplay.sh && ./Tools/notarize_netplay.sh ./artifact/${{ env.FILE_NAME }}.dmg
      - name: "Package ${{ matrix.build_type }}"
        if: success() && env.CERTIFICATE_MACOS_APPLICATION == null)
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          CERTIFICATE_MACOS_APPLICATION: ${{ secrets.CERTIFICATE_MACOS_APPLICATION }}
        run: |
          cd  ./build/Binaries
          zip -r "${{ env.FILE_NAME }}.zip" Ishiiruka\ Dolphin.app
          mv "${{ env.FILE_NAME }}.zip" ../../artifact/
      - name: "Publish"
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.artifact_name }}
          path: "./artifact/"
      - name: "Publish"
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.artifact_name }}
          path: "./artifact/"
      #- name: "Enable Admin Debugging via SSH (if failed)"
      # if: failure()
      # uses: luchihoratiu/debug-via-ssh@main
      # with:
      #  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
      #   SSH_PASS: ${{ secrets.NGROK_PASS }}