name: PR Builds x64

on:
  push:
    branches:
        - Dev
    paths-ignore:
        - "**.md"
        - "**.ini"
  pull_request:
    branches: [ Dev ]
    paths-ignore:
      - "**.md"
      - "**.ini"

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact_name: windows
    env:
      DXSDK_DIR: "C:\\Program Files (x86)\\Microsoft DirectX SDK (June 2010)\\"
    name: "Windows Dolphin"
    runs-on: windows-2019
    steps:
      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1
      - name: "Build Dolphin"
        run: |
          mkdir -p ${{ github.workspace }}/Binary/x64/
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: "Build Updater"
        working-directory: ${{ github.workspace }}
        shell: cmd
        run: |
          git clone https://github.com/Birdthulu/FPM-Win-Updater
          cd FPM-Win-Updater
          nuget restore ${{ github.workspace }}\FPM-Win-Updater\DolphinUpdater.sln
          msbuild /p:Configuration=Release /p:Platform="Any CPU" ${{ github.workspace }}\FPM-Win-Updater\DolphinUpdater.sln
          cd DolphinUpdater\bin\Release
          copy /b /v /y Updater.exe ${{ github.workspace }}\Binary\x64\
      - name: "Build Replay Manager"
        working-directory: ${{ github.workspace }}
        shell: cmd
        run: |
          git clone https://github.com/Birdthulu/Dolphin-Replay-Manager
          cd Dolphin-Replay-Manager
          msbuild /p:Configuration=Release /p:Platform="Any CPU" "${{ github.workspace }}\Dolphin-Replay-Manager\Bird's Replay Manager.sln"
          cd "Bird's Replay Manager\bin\Release"
          copy /b /v /y "Bird's Replay Manager.exe" ${{ github.workspace }}\Binary\x64\
      - name: "Prepare Artifact"
        working-directory: ${{ github.workspace }}
        run: |
          cd .\Binary\x64\
      - name: Package Artifact
        working-directory: ${{ github.workspace }}
        run: |
          $FILE_NAME="${{ matrix.artifact_name }}.zip"
          mkdir artifact
          cd .\Binary\x64\
          fsutil file createnew portable.txt 0
          7z a $FILE_NAME .\*
          move $FILE_NAME ..\..\artifact\
      - name: "Publish"
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.artifact_name }}
          path: "./artifact/"